version: '1'
services:
  mongo:
    image: mongo
    container_name: mongodb
    hostname: mongo
    restart: unless-stopped
    ports:
      - 27000:27017
    environment:
      - MONGO_INITDB_DATABASE=studentDB
    networks:
      - main-network
    command: ["--bind_ip","0.0.0.0"]

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: springapp
    container_name: student-app
    restart: on-failure
    depends_on:
      - mongo
    ports:
      - 8080:8080
    networks:
      - main-network
    links:
      - mongo

networks:
  main-network:
    external:
      name: student-network